<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.14" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
      <PackageReference Include="SendGrid" Version="9.29.3" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
      <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Category\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Order\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Order\Track.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Areas\ProjectManagement\Views\Product\Create.cshtml" />
      <AdditionalFiles Include="Areas\ProjectManagement\Views\Product\Delete.cshtml" />
      <AdditionalFiles Include="Areas\ProjectManagement\Views\Product\Details.cshtml" />
      <AdditionalFiles Include="Areas\ProjectManagement\Views\Product\Edit.cshtml" />
      <AdditionalFiles Include="Areas\ProjectManagement\Views\Product\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\Product\Image\" />
    </ItemGroup>

</Project>
